### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by JohannHM** [tminka/lightspeed#1]
First of all, thanks timnka for your effort. It looks like very useful. However, I couldnt find any examplo of how to compute the flops. There many functions related.
In my case I just want to compute the flops when coompute de frobenius norm of the la palcian of two exponential matrices.
Thanks in advance.
JohannM.

**Comment by tminka** [comment]
Scroll down to see the README file.  Click on the links in the README to see examples of flop counting.

**Comment by JohannHM** [comment]
I didnt notice that. Thank so much. I'll check it out and comeback then if I need it. Best regards tminka

**Comment by RoyiAvital** [comment]
Hi,

Does it work on MATLAB R2018a with MSVC 2017?
