### ISSUE TITLE
Link down

### ISSUE THREAD

**Issue by fjramireg** [tminka/lightspeed#2]
Dear Tminka,
Some year ago I acceded to the previous site of lightspeed and I observed many advices to speedup the Matlab code. I'm trying to access to the link http://tminka.github.io/software/matlab/, but the page does not exist.
Best!
Francisco

**Comment by erikr** [comment]
try https://tminka.github.io/software/matlab.html

and https://ubcmatlabguide.github.io/html/speedup.html
