### ISSUE TITLE
no random.lib

### ISSUE THREAD

**Issue by anxuthu** [tminka/lightspeed#3]
Dear tminka,

Thanks for this wonderful toolkit. But I run into a problem in line 137 of install_lightspeed.m indicating that there is no random.lib file. Could you figure it out? I use matlab 2018a and the mex compiler is vc++2017.

**Comment by tminka** [comment]
There must have been a compilation error before that point.  Can you send the full output?  It might help me isolate the problem.

**Comment by anxuthu** [comment]
I changed it into mingw compiler and it worked. It seems to be some path problem. Thanks!
