### ISSUE TITLE
Warning on osx 10.12; deprecated functions

### ISSUE THREAD

**Issue by gaming-hacker** [tminka/lightspeed#4]
wow, i've used lightspeed since version 2.2?

using xcode 9.1, osx 10.12 there are 2 warnings

all of the tests ran

Time for binornd: 0.457948
Time for randbinom: 0.0284098 (16.1194 times faster)
Time for binornd: 0.364998
Time for randbinom: 0.025445 (14.3445 times faster)
Time for binornd: 0.363836
Time for randbinom: 0.0248796 (14.6239 times faster)
Time for binornd: 0.364997
Time for randbinom: 0.0250529 (14.569 times faster)
Time for binornd: 0.364939
Time for randbinom: 0.0245121 (14.8881 times faster)
Time for binornd: 0.365124
Time for randbinom: 0.024416 (14.9543 times faster)
Time for binornd: 0.375789
Time for randbinom: 0.0244687 (15.358 times faster)

still find it weird matlab in all these years hasn't picked up on your code and fixed their routines.  

excellent routines.

Compiling lightspeed 2.7 mex files...
/Volumes/Swap/Documents/Matlab/Lib/lightspeed_repo/int_hist.c:42:9: warning: assigning to 'mxArray *' (aka 'struct mxArray_tag *') from 'const mxArray *' (aka 'const struct mxArray_tag *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        nArray = prhs[0];
               ^ ~~~~~~~
1 warning generated.

/Volumes/Swap/Documents/Matlab/Lib/lightspeed_repo/util.c:49:7: warning: 'finite' is deprecated: first deprecated in macOS 10.9 [-Wdeprecated-declarations]
  if(!finite(b)) return a;
      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/math.h:757:12: note: 'finite' has been explicitly marked deprecated here
extern int finite(double) __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0, __MAC_10_9, __IPHONE_NA, __IPHONE_NA);
           ^
/Volumes/Swap/Documents/Matlab/Lib/lightspeed_repo/util.c:235:7: warning: 'finite' is deprecated: first deprecated in macOS 10.9 [-Wdeprecated-declarations]
  if(!finite(x)) return x;
      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/math.h:757:12: note: 'finite' has been explicitly marked deprecated here
extern int finite(double) __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0, __MAC_10_9, __IPHONE_NA, __IPHONE_NA);

**Comment by tminka** [comment]
Thanks, this is now fixed.
